### PR TITLE
Add attributeWillRewrite options to BaseColumn for avoid use setters reason

### PR DESCRIPTION
**Pull request by bscheshirwork**
#249

### CODE REVIEW

**Comment by bscheshirwork** [comment]
@unclead can you approve this PR please?

**Comment by unclead** [comment]
i don't like the solution. BaseColumn doesn't have to know anything about MultipleInput or TableInput.
I need time to think if we can solve it in other way. If this issue is critical for you you can override the method in your class and pass it via option columnClass

**Comment by bscheshirwork** [comment]
Also we can use list of "trusted" widgets as param too

**Comment by bscheshirwork** [comment]
So... We can remove check of `MultipleInput` or add another "trusted" widget `TableInput`...

**Comment by bscheshirwork** [comment]
Another way - use closure with default representation 
```php
function($model, $value) {
$model->{$this->name} = $value;
}
```

**Comment by unclead** [comment]
yes i was thinking about closure too because it is more configurable, but from other side this option is quite useless because it covers only particular case (for more then 3 years you are the one who noticed this issue)

**Comment by unclead** [comment]
i prefer more straightforward solution 25b7a4b39a49db2c4287cd8b3ded740da418ea81 because i don't see any side effects and it solves an original issue

**Pull request closed without merging**
