### PR TITLE
Add template for input

### PR DESCRIPTION
**Pull request by bscheshirwork**
#264 

So... I create this commit based at previous #274 
Again.

:smile_cat:

### CODE REVIEW

**Comment by unclead** [comment]
To be honest i don't like how ListRenderer markup looks like. I would better to leave current implementation on top of table and add new renderer DivRenderer or something else. E.g. action buttons don't follow the grid and it looks ugly. Others changes looks good.

**Comment by unclead** [comment]
@bscheshirwork up

**Comment by bscheshirwork** [comment]
Just add in next commit. Previous PR is not changes

**Comment by bscheshirwork** [comment]
@unclead

**Comment by unclead** [comment]
@bscheshirwork  don't forget to update Wiki

**Comment by unclead** [comment]
i released version 2.19.0

**Comment by bscheshirwork** [comment]
https://packagist.org/packages/unclead/yii2-multiple-input#dev-master refer to https://github.com/unclead/yii2-multiple-input/commit/3f5447faf923d0e96185199ba76bafe37819a5b1

not to current https://github.com/unclead/yii2-multiple-input/commit/753e7be9c6c6a4f90c70d3be8950d4c83b64dd54

**Comment by bscheshirwork** [comment]
@unclead 

Also latest tag is not included

dev-master
2.18.0
2.17.1
2.17.0
2.16.0
2.15.0
2.14.0
2.13.0
2.12.0
2.11.3
2.11.2
2.11.1
2.11.0
2.10.0
2.9.0
2.8.2
2.8.1
2.8.0
2.7.1
2.7.0
2.6.1
2.6.0
2.5.0
2.4.0
2.3.2
2.3.1
2.3.0
2.2.0
2.1.1
2.1.0
2.0.x-dev
2.0.1
2.0.0
1.4.1
1.4.0
1.3.1
1.3.0
1.2.19
1.2.18
1.2.17
1.2.16
1.2.15
1.2.14
1.2.13
1.2.12
1.2.11
1.2.10
1.2.9
1.2.8
1.2.7
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
1.2.1
1.2.0
1.1.0
1.0.4
1.0.3
1.0.2
1.0.1
1.0.0
dev-client-validation
dev-custom_renderer

**Comment by unclead** [comment]
i guess something wrong was with packagist. I forced an update of repo information via packagist UI

**Pull request merged**
