### PR TITLE
add key support

### PR DESCRIPTION
**Pull request by ivansal**

### CODE REVIEW

**Comment by unclead** [comment]
Can you provide the example of usage? Need to update README as well, e.g. add new block to a tips section

**Comment by unclead** [comment]
Merged via 06b3d24c9d0d1d2abd9d893e9705ee490f2b9755
Thank you for your support :+1:

**Comment by ivansal** [comment]
can you add new version pls?

**Comment by unclead** [comment]
I'll release a new version after merge last opened PR, most probably today evening

**Pull request merged**
