### PR TITLE
add support "\yii\web\JsExpression"

### PR DESCRIPTION
**Pull request by Spell6inder**
to replaceIndexPlaceholderInOptions

### CODE REVIEW

**Comment by unclead** [comment]
can you show an example where you really need JsExpression instead of a raw string?

**Comment by Spell6inder** [comment]
If parameter must be anonymous function.
For example:
#280 or
``` php
// ...
        [
                'type' => \kartik\widgets\Select2::class,
// ...
                'pluginOptions' => [
                    'ajax' => [
                        'data' => new \yii\web\JsExpression('function(params) { 
                        return {q:params.term,page: params.page,id:$("#select{multiple_index}").val()}; }
                        '),
                    ],
                ]
            ]
        ],
// ...
```

**Comment by Spell6inder** [comment]
but I noticed that it still does not work properly - the js configuration has no placeholder

**Comment by unclead** [comment]
because you use wrong placeholder `{multiple_index}`, you have to add widget ID e.g. `{multiple_index_my_id}`

**Comment by Spell6inder** [comment]
> because you use wrong placeholder `{multiple_index}`, you have to add widget ID e.g. `{multiple_index_my_id}`

This is just an example, I tested with `multiple_index_my_id` and got 0 in the template
``` javascript
function(params) { return {q:params.term,page: params.page,id:$("#select0").val()}; }
```
and all added rows by clicking "Add" use  `$("#select0").val()`

in any case, this is a proposal, not a critical necessity)))
and you can achieve the desired result by taking data from the html attributes

**Comment by unclead** [comment]
closed via 6ee2001f8b108f6c4e4c6dfdf9acfb11d4429554

**Pull request closed without merging**
